# Generated by Django 3.2 on 2023-06-17 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
          migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.DecimalField(decimal_places=0, max_digits=10)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2023, 6, 17, 19, 52, 16, 59253))),
                ('subject', models.CharField(max_length=20, verbose_name='科目')),
                ('tea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.teacher')),
            ],
            options={
                'verbose_name': '上载文件',
                'verbose_name_plural': '上载文件',
                'db_table': 'FileInfo',
            },
        ),
    ]
