# Generated by Django 4.2.1 on 2023-07-15 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_auto_20230617_1952"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fillquestionanswer",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="questionanswer",
            name="rate",
        ),
        migrations.AddField(
            model_name="fillquestion",
            name="order",
            field=models.IntegerField(
                choices=[(1, "空格输入有序"), (2, "空格输入无序")], default=1, verbose_name="顺序"
            ),
        ),
        migrations.AddField(
            model_name="fillquestionanswer",
            name="all",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fillquestionanswer",
            name="right",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grade",
            name="paper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.paper",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="overtime",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="paper",
            name="pid",
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="all",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="right",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 15, 15, 21, 48, 815190)
            ),
        ),
        migrations.AlterField(
            model_name="fillquestion",
            name="level",
            field=models.CharField(
                choices=[
                    ("4", "hard"),
                    ("1", "easy"),
                    ("2", "normal"),
                    ("5", "hell"),
                    ("3", "difficult"),
                ],
                max_length=10,
                verbose_name="难度等级",
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="level",
            field=models.CharField(
                choices=[
                    ("4", "hard"),
                    ("1", "easy"),
                    ("2", "normal"),
                    ("5", "hell"),
                    ("3", "difficult"),
                ],
                max_length=10,
                verbose_name="难度等级",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="level",
            field=models.CharField(
                choices=[
                    ("4", "hard"),
                    ("1", "easy"),
                    ("2", "normal"),
                    ("5", "hell"),
                    ("3", "difficult"),
                ],
                max_length=10,
                verbose_name="难度等级",
            ),
        ),
    ]
